### ISSUE TITLE
[Question] Is this project still active ?

### ISSUE THREAD

**Issue by hydroflame** [fetlife/ios#36]

**Comment by johnbaku** [comment]
We don't have someone working on it full-time anymore. So it's not dead... but not exactly thriving... kind of on a hiatus!

But if anyone ever has a fix or anything they can always create a PR and we will review it and get it merged.

**Comment by alias1** [comment]
@johnbaku I don't have the time at the moment per se, but one feature I've waned forever is a better ability to get my events on my calendar. I had high hopes with this app popping up, but best I could tell last time I looked, there were no calendar related API's exposed. Is this something that exists at a backend level? And if so, what's the likelihood of being able to make use of them? In this app or otherwise? The other alternative I've seen used is basically scraping, but obviously that is a pretty inefficient/ducky method, and probably violates terms of use.

**Comment by hydroflame** [comment]
I'm currently revamping the whole app so if you give me time I'll see what I can do
